server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要 求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #lb代表的loadBlance的意思，而且lb后面的//必须加上，不然会报错
          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            #- Query=username, \d+ #指定请求参数的限制
            #- Method=GET #指定请求类型
            #- Host=**.mordo.com #主机名称
            #- Header=X-Request-Id, \d+ #携带指定的请求头和值
            #- Cookie=username,shl #带指定的cookie范围，第一个参数是cookie的名字，后面的是正则表达式
            #- After=2020-12-05T16:44:58.931+08:00[Asia/Shanghai] #满足在某个时间之后
            #- Before=2020-12-05T16:58:58.931+08:00[Asia/Shanghai] #满足在某个时间之前
            #- Between=2020-12-05T16:44:58.931+08:00[Asia/Shanghai],2020-12-05T16:58:58.931+08:00[Asia/Shanghai] #满足在某个时间范围之内
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


